// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FexitDbContext))]
    [Migration("20260917205701_RenombrarEquipoAControlador")]
    partial class RenombrarEquipoAControlador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Domain.Entities.Accion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("ControladorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinicionParametrosJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDireccion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsaEnclavamientos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Acciones_Codigo");

                    b.HasIndex("ControladorId");

                    b.ToTable("Acciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acciones_Modo", "Modo IN ('lectura','escritura')");

                            t.HasCheckConstraint("CK_Acciones_TipoDireccion", "TipoDireccion IS NULL OR TipoDireccion IN ('Coil','DiscreteInput','HoldingRegister','InputRegister','S7Bit','S7Byte','S7Word','S7DWord','S7Real')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Controlador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("S7300");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puerto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Slot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("plc");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Controladores_Nombre");

                    b.ToTable("Controladores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Controladores_Modelo", "Modelo IN ('S7200','S7300','S7400','S71200','S71500')");

                            t.HasCheckConstraint("CK_Controladores_Protocolo", "Protocolo IN ('SiemensS7','ModbusTcp','Simulado','HuiduSdk')");

                            t.HasCheckConstraint("CK_Controladores_Puerto", "Puerto > 0 AND Puerto <= 65535");

                            t.HasCheckConstraint("CK_Controladores_TipoEquipo", "TipoEquipo IN ('plc','cartel')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Enclavamiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<long>("ControladorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TipoDireccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoresOk")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Id");

                    b.HasIndex("ControladorId", "Orden")
                        .HasDatabaseName("IX_Enclavamientos_Controlador_Orden");

                    b.ToTable("Enclavamientos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enclavamientos_TipoDireccion", "TipoDireccion IN ('Coil','DiscreteInput','HoldingRegister','InputRegister','S7Bit','S7Byte','S7Word','S7DWord','S7Real')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.Accion", b =>
                {
                    b.HasOne("Domain.Entities.Controlador", "Controlador")
                        .WithMany()
                        .HasForeignKey("ControladorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Controlador");
                });

            modelBuilder.Entity("Domain.Entities.Enclavamiento", b =>
                {
                    b.HasOne("Domain.Entities.Controlador", "Controlador")
                        .WithMany("Enclavamientos")
                        .HasForeignKey("ControladorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controlador");
                });

            modelBuilder.Entity("Domain.Entities.Controlador", b =>
                {
                    b.Navigation("Enclavamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
